<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/10 0010
 * Time: 14:13
 */

namespace app\manage\controller;


use app\common\controller\Manage;

class Banks extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "banks";
        $this->model = model( 'banks');
        $this->isValidate = false;
    }
}