<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/18 0018
 * Time: 14:48
 */

namespace app\manage\controller;
use app\common\controller\Manage;

class Business extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "business";
        $this->model = model( "business");
    }

    /**
     * 2019/6/18 0018 15:44
     * @desc
     * @ApiParams
     * @ApiReturnParams
     */
    public function add()
    {
        if( request()->isAjax() && request()->isAjax() ){
            $password = $this->request->param( 'password', '');
            if( empty( $password ) ){
                $this->error( "密码不能为空！");
            }
            if( !preg_match('/^\w{6,12}$/', $password) ){
                $this->error( "请输入6-12位由数字字母下划线组成的密码！");
            }
            $data = $this->request->param();
            if( $data['frozen_money'] > $data['money'] ){
                $this->error( "冻结金额不能超过账户余额！");
            }
            $data['salt'] = getSalt();
            $data['password'] = encode_password( $password, $data['salt'] );
            $data['create_time'] = time();

            if( $this->isValidate ){
                $validate = validate($this->table);
                if (!$validate->check($data)) {
                    $this->error($validate->getError());
                }
            }
            $data['shop_sn'] = $this->model->max("shop_sn")+1;
            $res = $this->model->allowField( true )->data($data)->isUpdate( false )->save();
            if ($res) {
                $this->success('新增成功');
            }
            $this->error('新增失败！');
        }
        return $this->fetch();
    }

    /**
     * 2019/6/18 0018 16:24
     * @desc 编辑商户信息
     * @ApiParams
     * @ApiReturnParams
     */
    public function edit()
    {
        $id = $this->request->param('id', 0, 'intval');
        if (empty($id)) {
            $this->error("参数错误！");
        }
        if( request()->isAjax() && request()->isAjax() ){
            $data = $this->request->param();
            $password = $this->request->param( 'password', '');
            if( !empty( $password ) ){
                if( !preg_match('/^\w{6,12}$/', $password) ){
                    $this->error( "请输入6-12位由数字字母下划线组成的密码！");
                }
                $data['salt'] = getSalt();
                $data['password'] = encode_password( $password, $data['salt'] );
            };
            if( $data['frozen_money'] > $data['money'] ){
                $this->error( "冻结金额不能超过账户余额！");
            }
            if( $this->isValidate ){
                $validate = validate($this->table);
                if (!$validate->check($data)) {
                    $this->error($validate->getError());
                }
            }
            $res = $this->model->allowField( true )->data($data)->isUpdate( true )->save();
            if ($res) {
                $this->success('更新成功');
            }
            $this->error('更新失败！');
        }
        $data = $this->model->where('id', $id)->find();
        $this->assign('data', $data);
        return $this->fetch();
    }
    /**
     * 2019/6/18 0018 15:52
     * @desc审核商户信息
     * @ApiParams
     * @ApiReturnParams
     */
    public function check()
    {
        $id = $this->request->param( 'id', 0, 'intval');
        if( empty( $id ) ){
            $this->error( "参数错误！");
        }
        if( request()->isPost() ){
            $data = $this->request->post('');
            $data['check_time'] = time();
            $res = $this->model->allowField(true)->where( ['id'=>$id] )->data( $data )->update();
            if( $res ){
                $this->success( "设置成功！");
            }
            $this->error( "请稍后再试！");
        }
        $where = [
            'id' => $id,
            'delete_time'   => 0
        ];
        $data = $this->model->where( $where )->field( 'id,name,check,check_desc,check_time')->find();
        if( !$data ){
            $this->error( "商户不存在！");
        }
        $this->assign( "data", $data );
        return $this->fetch();
    }

    /**
     * 2019/6/20 0020 10:02
     * @desc手动设置商户余额
     * @ApiParams
     * @ApiReturnParams
     */
    public function account()
    {
        $id = $this->request->param('id',0,'intval');
        if( empty( $id ) ){
            $this->error( "请选择指定商户！");
        }
        $data = $this->model->where( "id",$id)->field( "id,money,frozen_money")->find();
        $this->assign( "data", $data);
        return $this->fetch();
    }

}