<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/15 0015
 * Time: 10:15
 */

namespace app\manage\controller;
use app\common\controller\Manage;

class Config extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model( 'Config');
        $this->table = "config";
    }

    public function index()
    {
        return $this->fetch();
    }

    public function insert()
    {
        if( request()->isAjax() && request()->isPost() ){
            $param = $this->request->post();
            //获取配置
            $list = $lists = [];
            foreach ( $param as $key => $val ){
                $id = $this->model->where( ['vname'=>$key] )->value('id');
                if( $id ){
                    $list[] = ['value'=>$val,'id'=>$id];
                } else {
                    $lists[] = ['value'=>$val,'vname'=>$key];
                }
            }
            if( count( $list ) > 0 ) $this->model->saveAll( $list );
            if( count( $lists ) > 0 ) $this->model->saveAll( $lists );
            session("deploy", null);
            $this->success("更新成功！");
        }
        $this->error("请求方式错误！");
    }
}