<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/18 0018
 * Time: 14:08
 */

namespace app\manage\controller;


use app\common\controller\Manage;

class Log extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "Log";
        $this->model = model($this->table);
    }

    public function se()
    {
        halt(session('userInfo'));
    }

}