<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/17 0017
 * Time: 13:14
 */

namespace app\manage\controller;
use app\common\controller\Manage;

class Menu extends Manage
{
    public  function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "Menu";
        $this->model = model( "Menu");
    }
}