<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/27 0027
 * Time: 17:07
 */

namespace app\manage\controller;


use app\common\controller\Manage;
use think\Db;

/**
 * Class Mysql 数据库管理
 * @package app\manage\controller
 */
class Mysql extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model( 'mysql');
    }

    public function index()
    {
        //获取所有的数据表
        $sql = "show tables";
        $data = Db::query( $sql );
        echo "<pre>";
        var_dump( $data );
    }
}