<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/19 0019
 * Time: 14:43
 */

namespace app\manage\controller;
use app\common\controller\Manage;

class Notice extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "notice";
        $this->model = model( $this->table );
    }

    public function isTop()
    {
        if (request()->isAjax() && request()->isPost()) {
            $id = request()->param('id', 0, 'intval');
            if (empty($id)) {
                $this->error('参数错误');
            }
            $value = request()->param('value', 0, 'intval');
            $where = ['id' => $id];
            $res = $this->model->where($where)->update([ 'is_top' => $value]);
            if ($res) {
                operaLog('置顶公告--id号为'.$id);
                $this->success('设置成功！');
            } else {
                $this->error('请重新设置！');
            }
        }
        $this->error('非法请求类型！');
    }
}