<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/28 0028
 * Time: 16:07
 */

namespace app\manage\controller;
use app\common\controller\Manage;
use think\Validate;

class Setting extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model( "setting");
        $this->table = "setting";
    }

    public function index()
    {
        if( request()->isAjax() && request()->isPost() ){
            $data = $this->request->param();
            //校验数据
            $rule = [
                ['key','require',"请输入通讯密钥"],
                ['notifyUrl','require|url',"请输入异步回调地址|异步回调地址不合法"],
                ['returnUrl','require|url',"请输入支付完成后跳转地址|支付完成后跳转地址不合法"],
                ['close','require',"请输入创建的订单几分钟后失效"]
            ];
            $validate = new Validate();
            $validate->rule( $rule );
            if( !$validate->check( $data ) ){
                $this->error( $validate->getError() );
            }
            foreach ( $data as $key => $val ){
                $this->model->allowField( true )->save( ['vvalue'=>$val],['vkey'=> $key]);
            }
            $this->success( "提交成功！");
        }
        //获取后端配置信息
        $data = $this->model->select();
        $res = [];

        foreach ( $data as $val ){

            $res[ $val['vkey'] ] = $val['vvalue'];
        }
        $this->assign( 'data', $res );
        return $this->fetch();
    }

    public function getSettings(){
        $data = $this->model->select();
        $res = [];
        $time = [
            "lastheart","lastpay","jkstate"
        ];
        foreach ( $data as $val ){
            $v = in_array( $val['vkey'], $time ) && !empty( $val['vvalue'])? date("Y-m-d H:i:s", $val['vvalue'] ) : $val['vvalue'];
            $res[ $val['vkey'] ] = $v;
        }
        $this->success( "成功！",1,$res);
    }
}