<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/17 0017
 * Time: 9:18
 */

namespace app\manage\controller;
use app\common\controller\Manage;

class User extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "User";
        $this->model = model( "User");
    }

    public function add()
    {
        if( request()->isAjax() && request()->isAjax() ){
            $password = $this->request->param( 'password', '');
            if( empty( $password ) ){
                $this->error( "密码不能为空！");
            }
            if( !preg_match('/^\w{6,12}$/', $password) ){
                $this->error( "请输入6-12位由数字字母下划线组成的密码！");
            }
            $data = $this->request->param();
            $data['salt'] = getSalt();
            $data['password'] = encode_password( $password, $data['salt'] );
            $data['create_time'] = time();
            if( $this->isValidate ){
                $validate = validate($this->table);
                if (!$validate->check($data)) {
                    $this->error($validate->getError());
                }
            }
            $res = $this->model->allowField( true )->data($data)->isUpdate( false )->save();
            if ($res) {
                $this->success('新增成功');
            }
            $this->error('新增失败！');
        }
        return $this->fetch();
    }

    public function edit()
    {
        $id = $this->request->param('id', 0, 'intval');
        if (empty($id)) {
            $this->error("参数错误！");
        }
        if( request()->isAjax() && request()->isAjax() ){
            $data = $this->request->param();
            $password = $this->request->param( 'password', '');
            if( !empty( $password ) ){
                if( !preg_match('/^\w{6,12}$/', $password) ){
                    $this->error( "请输入6-12位由数字字母下划线组成的密码！");
                }
                $data['salt'] = getSalt();
                $data['password'] = encode_password( $password, $data['salt'] );
            };
            if( $this->isValidate ){
                $validate = validate($this->table);
                if (!$validate->check($data)) {
                    $this->error($validate->getError());
                }
            }
            $res = $this->model->allowField( true )->data($data)->isUpdate( true )->save();
            if ($res) {
                $this->success('更新成功');
            }
            $this->error('更新失败！');
        }
        $data = $this->model->where('id', $id)->find();
        $this->assign('data', $data);
        return $this->fetch();
    }

    /**
     * 2019/6/19 0019 9:21
     * @desc个人中心
     * @ApiParams
     * @ApiReturnParams
     */
    public function center()
    {
        return $this->fetch();
    }
    /**
     * 2019/6/17 0017 16:34
     * @desc 配置用户权限
     * @ApiParams
     * @ApiReturnParams
     */
    public function auth()
    {
        $id = request()->param( 'id', 0, 'intval');
        if( empty( $id ) ) {
            die("参数错误！");
        }
        if( request()->isAjax() && request()->isPost() ){
            $rule = $this->request->param('rule', '');
            $res = $this->model->where('id',$id)->update(['rule' => $rule, 'update_time' => time()]);
            if( $res ){
                $this->success( "权限配置成功！");
            }
            $this->error("系统繁忙，请稍后再试！");
        }
        $where = [
            'id' => $id,
            'status'    => 1
        ];
        $rule = $this->model->where( $where )->field('rule')->find();
        if( $rule == false ){
            die('该数据不存在或为隐藏状态！');
        }
        $this->assign( 'rule', $rule['rule']);
        $this->assign('id', $id);
        return $this->fetch();
    }
}