<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/18 0018
 * Time: 14:08
 */

namespace app\manage\controller;


use app\common\controller\Manage;

class Withdraw extends Manage
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "Withdraw";
        $this->model = model($this->table);
        $this->join = [
            ['business b', 'b.id = a.bus_id', 'left'],
            ['account c', 'c.business_id = a.bus_id', 'left']
        ];
        $this->field = "a.*,b.name,c.ali_name,c.ali_user,c.we_name,c.we_user,c.un_name,c.un_user,c.un_bank,c.un_branch";
    }

    /**
     *  提款审核
     * @return mixed
     * @throws \think\Exception
     */
    public function check_status()
    {
        $id = $this->request->param('id', 0, 'intval');
        if (empty($id)) {
            $this->error('参数错误');
        }
        $where = [
            'id' => $id,
            'delete_time' => 0
        ];
        $field = 'id,bus_id,status,check_desc,check_time,money,fee_type,fee,picture';
        $data = $this->model->where($where)->field($field)->find();
        $bus_name = db('business')->where('id', $data['bus_id'])->value('name');
        if ( request()->isPost() ) {
            $post_data = $this->request->param('');
            if (!isset($post_data['status'])) {
                $this->error('请选择审核状态');
            }
            if ( $data['status'] !== 0 && $data['status'] != $post_data['status']) {
                $this->error('已审核过,请勿重复审核');
            }
            if( $data['status'] == $post_data['status'] ){
                $result = $this->model->allowField(true)->save($post_data, ['id' => $id]);
                if( $result ){
                    $this->success( "设置成功！");
                }
                $this->error( "设置失败！");
            }

            $post_data['check_time'] = time();
            $post_data['bus_id']    = $data['bus_id'];
            $result = $this->model->allowField(true)->save($post_data, ['id' => $id]);
            if ($result) {
                $post_data['fee'] = $data['fee'];
                $post_data['fee_type'] = $data['fee_type'];
                $this->model->changeWithdraw( $post_data );
                operaLog($this->admin_id . '对商户(' . $bus_name . ')提款审核');
                $this->success("设置成功！");
            }
            $this->error("请稍后再试！");
        }
        $data['check_time'] = date('Y-m-d H:i:s', $data['check_time']);
        $this->assign('data', $data);
        return $this->fetch();
    }

}