<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/18 0018
 * Time: 14:08
 */

namespace app\manage\controller;


use app\common\controller\Manage;

class Withdraw extends Manage
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "Withdraw";
        $this->model = model($this->table);
    }

    public function index()
    {
        if ($this->request->isPost() && $this->request->isAjax()) {
            $page = $this->request->param('page', 1, 'intval');
            $per = $this->request->param('limit', 10, 'intval');
            $this->order = $this->request->param('order', $this->order);
            $where = [
                'delete_time' => 0,
            ];
            $param = $this->request->param();
            foreach ($param as $key => $val) {
                $ps = substr($key, 0, 2);
                $vl = substr($key, 2);
                switch ($ps) {
                    case 'l-':
                        if (!empty($val)) $where[$vl] = ['like', '%' . $val . '%'];
                        break;
                    case 'e-':
                        if (!empty($val)) $where[$vl] = $val;
                        break;
                    case 'i-':
                        if (!empty($val)) $where[$vl] = ['in', $val];
                        break;
                    default:
                        break;
                }
            }
            $stime = $this->request->param('stime', 0);

            $ltime = $this->request->param('ltime', 0);
            $bus_name = $this->request->param('bus_name', '');
            $w_id = $this->request->param('w_id', 0);
            if (empty($stime) && !empty($ltime)) {
                $ltime = strtotime($ltime);
                $where['create_time'] = ['<=', $ltime];
            }
            if (!empty($stime) && empty($ltime)) {
                $stime = strtotime($stime);
                $where['create_time'] = ['>', $stime];
            }
            if (!empty($stime) && !empty($ltime)) {
                $ltime = strtotime($ltime);
                $stime = strtotime($stime);
                $where['create_time'] = ['between', [$stime, $ltime]];
            }
            if (!empty($bus_name)) {
                $bus = db('business')->where(['name' => ['like', '%' . trim($bus_name) . '%']])->field('id')->select();
                if (!empty($bus)) {
                    $where['bus_id'] = ['in', array_column($bus, 'id')];
                } else {
                    $this->error('商户名称错误');
                }
            }
            if (!empty($w_id)) {
                $where['w_id'] = ['eq', $w_id];
            }
            $page = $page - 1;
            if (count($this->join) > 0) {
                $list = $this->model
                    ->alias('a')
                    ->join($this->join)
                    ->field($this->field)
                    ->where($where)
                    ->limit($page * $per, $per)
                    ->order($this->order)
                    ->select();
            } else {
                $list = $this->model
                    ->field($this->field)
                    ->where($where)
                    ->limit($page * $per, $per)
                    ->order($this->order)
                    ->select();
            }

            $sql = $this->model->getLastSql();
            $count = $this->model->where($where)->count();
            $data = [
                'list' => $list,
                'count' => $count,
                'sql' => $sql
            ];
            $this->success('获取成功！', '', $data);
        }
        return $this->fetch();
    }

    /**
     *  提款审核
     * @return mixed
     * @throws \think\Exception
     */
    public function check_status()
    {
        $id = $this->request->param('id', 0, 'intval');
        if (empty($id)) {
            $this->error('参数错误');
        }
        $where = [
            'id' => $id,
            'delete_time' => 0
        ];
        $field = 'id,status,check_desc,check_time,money';
        $data = $this->model->where($where)->field($field)->find();
        if (!$data) {
            $this->error('该申请不存在');
        }
        if (request()->post()) {
            $post_data = $this->request->param('');
            if (!isset($post_data['status'])) {
                $this->error('请选择状态');
            }
            $post_data['check_time'] = time();
            $result = $this->model->allowField(true)->save($post_data, ['id' => $id]);
            if ($result) {
                \app\manage\model\Withdraw::addWithdrawLog($post_data);
                operaLog('提款审核');
                $this->success("设置成功！");
            }
            $this->error("请稍后再试！");
        }
        $data['check_time'] = date('Y-m-d H:i:s', $data['check_time']);
        $this->assign('data', $data);
        return $this->fetch();
    }

    /**
     *  提款软删除
     */
    public function remove()
    {
        if (request()->isPost()) {
            $id = $this->request->param('id', 0, 'intval');
            if (!$id) {
                $this->error('参数错误');
            }
            $res = $this->model->where('id', $id)->find();
            if (!$res) {
                $this->error('商户不存在');
            }
            $res->delete_time = time();
            $result = $res->save();
            if (!$result) {
                $this->error('移除失败');
            }
            operaLog('提款列表删除');
            $this->success('移除成功');
        }
    }

}