<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/18 0018
 * Time: 14:39
 */

namespace app\common\controller;
use think\Controller;

class Business extends Controller
{
    /**
     * @var array 登录商户的信息
     */
    protected $userInfo;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    /**
     * 2019/6/18 0018 14:45
     * @desc检查商户是否登录
     * @ApiParams
     * @ApiReturnParams
     */
    public function checkLogin()
    {
        if( !session( "?business") ){
            $this->redirect( url("Login/index") );
        }
        $this->userInfo = model( 'business')->where('id', session('business')['id'])->find();
        $this->assign( "user", $this->userInfo);
    }
}