<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/9 0009
 * Time: 17:57
 */

namespace app\business\controller;

use app\common\controller\Business;
use think\Request;

class tlt extends Business
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public static function pay()
    {

    }


}