<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/19 0019
 * Time: 15:23
 */

namespace app\business\controller;
use app\common\controller\Business;

class User extends Business
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->table = "business";
        $this->model = model( "business");
    }

    /**
     * 2019/6/19 0019 15:24
     * @desc 商户基本信息
     * @ApiParams
     * @ApiReturnParams
     */
    public function profile()
    {
        return $this->fetch();
    }

    public function user_passageway_list()
    {
        $user_passageway_list = model('user_passageway_list')->get($this->user->id);
        $this->assign('user_passageway_list', $user_passageway_list);
        return $this->fetch();
    }
}