<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/14 0014
 * Time: 13:19
 */

namespace app\daili\controller;
use app\common\controller\Business;
use think\Db;

/**
 * @desc 后端首页
 * Class Index
 * @package app\manage\controller
 */
class Index extends Business
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        return $this->fetch();
    }

    public function welcome()
    {
        /**
         * 公告信息返回
         */
        $notices = Db::name('notice')
            ->where('status',1)
            ->order('id','desc')
            ->field(['id','name','content'])
            ->select();
        $this->assign('notices',$notices);

        $loginLog = Db::name('login_log')->order('id','desc')->find();
        $loginLog['create_time'] = date('Y-m-d H:i:s',$loginLog['create_time']);
        $this->assign('logs',$loginLog);
        $this->assign('frozen_money',$this->user['frozen_money']);
        return $this->fetch();
    }
}